### PR TITLE
add support for UDMF maps

### LINKED ISSUE #29: UDMF support

### PR DESCRIPTION
**Pull request by ghost**
Supports all base games and ZDoom. The interface is mostly the same as the one for the original binary format, but the property names have been changed to match the UDMF field names. Fixes #29

### CODE REVIEW

**Comment by devinacker** [comment]
Hi, sorry for not being very quick to respond to this, been busy with a lot of other stuff. Hopefully I'll be able to properly check it out soon.

**Comment by devinacker** [comment]
Looks pretty good so far. I'll try doing some more in-depth testing and see what I think, but hopefully it can be merged soon.

One thing I was considering a while back regarding UDMF support would be to just have some kind of automatic translation of property names (performed at load/save time) between the names UDMF uses and the names that the existing MapEditor class uses, just to make the interfaces as similar as possible. I might see about adding something like that as well.

**Comment by zx64** [comment]
Thanks for this! I ran into an issue when converting some classic maps to UDMF. Turns out GZDoom is especially strict about boolean flags being written out as `true` or `false` instead of as ints, so the following changes made it happy:
```
  --- a/omg/udmf.py
  +++ b/omg/udmf.py
  @@ -345,14 +345,14 @@ class UMapEditor:
               for f in range(len(ULinedef.flags[namespace])):
                   flag = ULinedef.flags[namespace][f]
                   if flag:
  -                    setattr(block, flag, linedef.flags & (1 << f))
  +                    setattr(block, flag, bool(linedef.flags & (1 << f)))
               if hexencompat:
                   trigger = ((linedef.flags & 0x1c00) >> 10) - 1
                   if trigger >= 0 and trigger < len(ULinedef.triggers_hexen):
                       setattr(block, ULinedef.triggers_hexen[trigger], True)
               if hexencompat and linedef.action == 121:
                   for f in range(len(ULinedef.moreflags_hexen)):
  -                    setattr(block, ULinedef.moreflags_hexen[f], linedef.arg1 & (1 << f))
  +                    setattr(block, ULinedef.moreflags_hexen[f], bool(linedef.arg1 & (1 << f)))

           for sidedef in m.sidedefs:
```

**Comment by zx64** [comment]
Ran into some Hexen specific conversion issues:
* Player start Things rely on arg0 to control where you spawn when returning from another map. Without this, you get a bunch of voodoo dolls and usually don't start where intended.
* The `playercross` Linedef flag isn't being set on two sided lines with an action. There's several examples of this in MAP01, such as the lines that trigger script 7 (lines 37-40 etc.)

**Comment by devinacker** [comment]
Finally merged (with additions) in 9f15074b470fcf2d0b30614eb7af415d414219db. Thanks to @Xymph for lots of additional testing.

**Pull request closed without merging**
