### PR TITLE
Add new demo script slotfile.py

### PR DESCRIPTION
**Pull request by Xymph**
Another small demo script for WadIO usage, which I needed as [described here](https://doomwiki.org/wiki/User:XymphBot#slotfile.py).

### CODE REVIEW

**Comment by Xymph** [comment]
@devinacker : Given the prompt merge of the listdir script, the hesitation here becomes noticeable. Perhaps it's not such a useful demo script after all. No problem, it's fine if you prefer to reject it. Just wanted to clear that up so I can delete my local branch.

**Comment by devinacker** [comment]
It's definitely a bit niche compared to the other demo scripts, which is why I was a little unsure. I'll probably leave it open for now just to think about it.

**Comment by Xymph** [comment]
If you find one of my [other omg scripts](https://gist.github.com/Xymph) better suited, e.g. [texpackstats.py](https://gist.github.com/Xymph/d7e2e045c1669d5541a1c3aa623f6198) or [searchSpecial.py](https://gist.github.com/Xymph/8e2ebc7dbe69166b6045ce7464d4aa69), then I'd be happy to submit that instead.

**Comment by Xymph** [comment]
Could you wrap up your thinking process? :) It would be perfectly fine to reject the PR, I'd just like to clean up this old branch while we're in the flow of things.

**Comment by devinacker** [comment]
Yeah, I'm probably just going to hold off on it for now.

**Pull request closed without merging**
